version: "2"
services:
  redis:
    image: redis:alpine

  backend:
    build: .
    volumes:
     - .:/droplet
    depends_on:
     - redis

  proxy:
    image: haproxy:alpine
    ports:
     - 80:80
     - 443:443
    volumes:
     - ./haproxy:/haproxy
    depends_on:
     - backend
    command: ["haproxy", "-f", "/haproxy/haproxy.cfg"]
